name: mlc_app
description: "A new Flutter project."

publish_to: "Saidmirza"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  mask_text_input_formatter: ^2.7.0
  pinput: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - fonts/
    - assets/images/
    - assets/icons/
    - assets/l10n/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
